#!/usr/bin/perl
#
#-------------------------------------------------------------------------
# acpi scraper for i3blocks - (c)2018 Mark Page <mark@very3.net>
# Modified: Sat Aug 25 06:35:40 2018 -0500
# Requires: acpi, fonts-font-awesome
#-------------------------------------------------------------------------
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#-------------------------------------------------------------------------
#
use strict;
use warnings;

my $icons = {
  'CHG' => '',
  '0'   => '',
  '25'  => '',
  '50'  => '',
  '75'  => '',
  '100' => '',
};

my $which_battery = 0;
my $battery_icon  = '100';
my $icon_color    = '#00ff00';

if (defined($ENV{'BLOCK_INSTANCE'})) {
  $which_battery = $ENV{'BLOCK_INSTANCE'};
}

chomp(my $acpi = `acpi -b | grep 'Battery $which_battery'`); $acpi =~ s/\,|\%//g;
my (undef,undef,$charging,$percent,$time_left,undef) = split(/ /,$acpi);

if ($percent > 0 and $percent < 25) {
  $battery_icon = '0';
  $icon_color   = '#ff0000';
}
if ($percent >= 25 and $percent < 50) {
  $battery_icon = '25';
  $icon_color   = '#ffa500';
}
if ($percent >= 50 and $percent < 75) {
  $battery_icon = '50';
  $icon_color   = '#ffff00';
}
if ($percent >= 75 and $percent < 100) {
  $battery_icon = '75';
  $icon_color   = '#00ff00';
}

if ($charging !~ /discharging/i) {
  $battery_icon = 'CHG';
}

if ($time_left =~ m/rate/i) {
  $battery_icon = '0';
  $time_left    = '???';
  $icon_color   = '#ff0000';
}

if (defined($ARGV[0]) && $ARGV[0] eq 'long') {
  print $icons->{$battery_icon}.' '.$percent.'% ('.$time_left.")\n\n";
}
else {
  print $icons->{$battery_icon}.' '.$percent."%\n\n";
}
  
print $icon_color."\n";

exit(0);

__END__
