#!/usr/bin/perl
#
#-------------------------------------------------------------------------
# iostat scraper for i3blocks - (c)2018 Mark Page <mark@very3.net>
# Modified: Sat Aug 25 07:51:36 2018 -0500
# Requires: iostat, libjson-perl, fonts-font-awesome
#-------------------------------------------------------------------------
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#-------------------------------------------------------------------------
#
use strict;
use warnings;
use JSON;

my $icon_color = '#00ff00';

my $data = (decode_json(`iostat -c -o JSON`))->{'sysstat'}->{'hosts'}[0]->{'statistics'}[0]->{'avg-cpu'};

if ($data->{'user'} > 0 and $data->{'user'} <= 10) {
  $icon_color = '#00ff00';  
}
if ($data->{'user'} > 10 and $data->{'user'} <= 25) {
  $icon_color = '#ffff00';  
}
if ($data->{'user'} > 25 and $data->{'user'} <= 50) {
  $icon_color = '#ffa500';  
}
if ($data->{'user'} > 50) {
  $icon_color = '#ff0000';  
}


if (defined($ARGV[0]) && $ARGV[0] eq 'long') {
  print ' '.$data->{'user'}."%\n\n";
}
else {
  print ' '.$data->{'user'}."%\n\n";
}
  
print $icon_color."\n";

exit(0);

__END__
